### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by memetrollsXD** [teyvatps/teyvatps#4]
https://github.com/teyvatps/teyvatps/blob/9bc6df2c4702626aa44986a8fa21f800915d1f60/src/https/DispatchServer.php#L88-L90

dont hardcode this shit.. trash ps

**Comment by lilmayofuksu** [comment]
so true

**Comment by timing1337** [comment]
cry about it

**Comment by memetrollsXD** [comment]
uncry about it. ratio

**Comment by lilmayofuksu** [comment]
😱

**Comment by timing1337** [comment]
Fixed
