### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by anytarseir67** [teyvatps/teyvatps#6]
`PHP Fatal error:  Uncaught TypeError: Cannot assign null to property TeyvatPS\network\protocol\ProtocolDictonary::$nameToIdProtocol of type array in E:\test\teyvatps\src\network\protocol\ProtocolDictonary.php:31
Stack trace:
#0 E:\test\teyvatps\src\Start.php(17): TeyvatPS\network\protocol\ProtocolDictonary::init()
#1 E:\test\teyvatps\src\Start.php(34): TeyvatPS\run()
#2 {main}
  thrown in E:\test\teyvatps\src\network\protocol\ProtocolDictonary.php on line 31`

**Comment by timing1337** [comment]
Missing packetIds.json exits in the "data" folder

For reasons I can't publish them here, you'll have to figuring out thing yourself.
It's better to use [Grasscutter](https://github.com/Grasscutters/Grasscutter)

**Comment by anytarseir67** [comment]
i'm not though
![image](https://user-images.githubusercontent.com/42589471/178418346-37dd5179-aa92-4918-a7e4-f5ded7bb5cd8.png)

**Comment by timing1337** [comment]
Can you show your packetIds.json?
